MNSTR-3199: Booked room should remain visible on find rooms screen
cytrowski/roombelt pull request #3
Opened 2019-08-30 14:47 UTC by majalcmaj

Changed sorting mechanism to ignore the state change of a room which has
just been booked in "Find Rooms" screen.
![roombelt-find-other](https://user-images.githubusercontent.com/10534284/64029888-c03e4880-cb45-11e9-956e-74ccea7089a7.gif)

2019-09-02 22:07 UTC, cytrowski commented on frontend/src/apps/device/views/find-room/index.js
> +                            closeAllCalendarsView,
It looks like you are not using Prettier to format the code. Can you fix this PR formatting so that we can get rid of the unimportant diffs?

2019-09-02 22:08 UTC, cytrowski requested changes
I'd love to see the code formatting fixed. Other than that it looks fine - I'll be able to merge it this week.

2019-09-03 11:34 UTC, majalcmaj commented
@cytrowski Done :)

2019-10-08 09:54 UTC, cytrowski approved these changes

2019-10-08 09:54 UTC, merged